name: "Build"
on:
  push:
  pull_request:
jobs:
  build:
    name: "Build on JDK 11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"
      - run: ./gradlew check distTar
      - uses: actions/upload-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/apx.tar"
          retention-days: 1
  build-and-push-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/"
      - name: "Untar files"
        run: mkdir -p build/install && tar -xvf build/distributions/apx.tar -C $_
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to GHCR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: |
            ghcr.io/heapy/honeywell-iaq:main
            ghcr.io/heapy/honeywell-iaq:b${{ github.run_number }}
